#!/bin/zsh
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Wyllys Ingersoll
#
# Builds SolarBar.app from the SwiftPM release product, wraps it with a
# minimal Info.plist, bakes in an app icon generated by scripts/makeicon.swift,
# and ad-hoc codesigns the result.

set -euo pipefail

cd "$(dirname "$0")"

APP="SolarBar.app"
BUILD_DIR="build"

# 1. Release build
swift build -c release

# 2. Fresh bundle skeleton
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# 3. Executable
cp .build/release/solarbar "$APP/Contents/MacOS/solarbar"

# 4. App icon
mkdir -p "$BUILD_DIR"
swift scripts/makeicon.swift "$BUILD_DIR"
cp "$BUILD_DIR/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"

# 5. Info.plist
cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>     <string>en</string>
    <key>CFBundleExecutable</key>            <string>solarbar</string>
    <key>CFBundleIdentifier</key>            <string>com.wyllys.solarbar</string>
    <key>CFBundleInfoDictionaryVersion</key> <string>6.0</string>
    <key>CFBundleName</key>                  <string>SolarBar</string>
    <key>CFBundleDisplayName</key>           <string>SolarBar</string>
    <key>CFBundlePackageType</key>           <string>APPL</string>
    <key>CFBundleShortVersionString</key>    <string>1.0</string>
    <key>CFBundleVersion</key>               <string>1</string>
    <key>CFBundleIconFile</key>              <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>        <string>13.0</string>
    <key>LSUIElement</key>                   <true/>
    <key>NSHumanReadableCopyright</key>      <string>Copyright (c) 2026 Wyllys Ingersoll. MIT License.</string>
</dict>
</plist>
PLIST

# 6. Ad-hoc codesign
codesign --force --deep --sign - "$APP"

echo "Built $APP"
